version: '3.8'

services:
  # ----------------------------------------
  # SERVICE 1: Your FastAPI Backend
  # ----------------------------------------
  api:
    build: .
    container_name: ml_fastapi_backend
    # This overrides the Dockerfile CMD to run FastAPI with auto-reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # The Magic Trick: Syncs your local folder to the container
    
  # ----------------------------------------
  # SERVICE 2: Your Streamlit Dashboard
  # ----------------------------------------
  frontend:
    build: .
    container_name: ml_streamlit_frontend
    # This overrides the Dockerfile CMD to run Streamlit
    command: streamlit run steam.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api     # Tells Docker to start the API before the frontend
  